# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stone

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'

  pod 'Hero'

  target 'StoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StoneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
